services:
  backend:
    container_name: golf_backend
    build:
      context: ./laravel
      dockerfile: docker/local/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./laravel/.env
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./laravel:/var/www/html
    networks:
      - global_proxy

networks:
  global_proxy:
    external: true
